language: python
python:
  - 2.6
  - 2.7

env:
    - ZOOKEEPER_VERSION=3.3.6
    - ZOOKEEPER_VERSION=3.4.4

install:
    - make
    - make zookeeper

script:
    - make test

notifications:
  email:
    - adc@toolazydogs.com
