# File generated by hadoop record compiler. Do not edit.
"""
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""

class ExistsResponse:
    def __init__(self, stat):
        self.stat = stat

    def serialize(self, output_archive, tag):
        output_archive.start_record(tag)
        output_archive.write_record(self.stat, 'stat')
        output_archive.end_record(tag)

    def deserialize(self, input_archive, tag):
        input_archive.start_record(tag)
        self.stat = input_archive.read_record('stat')
        input_archive.end_record(tag)

    def __repr__(self):
        return 'ExistsResponse(%r)' % (self.stat)

    def __eq__(self, other):
        return self.stat == other.stat

    def __ne__(self, other):
        return not self.__eq__(other)

    def __hash__(self):
        return hash((self.stat))
