# File generated by hadoop record compiler. Do not edit.
"""
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
"""
from toolazydogs.zookeeper.packets.data.Stat import Stat


class GetChildren2Response:
    def __init__(self, children, stat):
        self.children = children
        self.stat = stat

    def serialize(self, output_archive, tag):
        output_archive.start_record(tag)
        output_archive.start_vector(self.children, 'children')
        if self.children != None:
            for e1 in self.children:
                output_archive.write_string(e1, 'e1')
        output_archive.end_vector(self.children, 'children')
        output_archive.write_record(self.stat, 'stat')
        output_archive.end_record(tag)

    def deserialize(self, input_archive, tag):
        input_archive.start_record(tag)
        len1 = input_archive.start_vector('children')
        if len1 != None:
            self.children = []
            for vidx1 in range(len1):
                e1 =  input_archive.read_string('e1')
                self.children.append(e1)
        else:
            self.children = None
        input_archive.end_vector('children')
        self.stat = Stat(None, None, None, None, None, None, None, None, None, None, None)
        input_archive.read_record(self.stat, 'stat')
        input_archive.end_record(tag)

    def __repr__(self):
        return 'GetChildren2Response(%r, %r)' % (self.children, self.stat)

    def __eq__(self, other):
        return self.children == other.children and self.stat == other.stat

    def __ne__(self, other):
        return not self.__eq__(other)

    def __hash__(self):
        return hash((self.children, self.stat))
