name: release-main

on:
  release:
    types: [published]
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env

      - name: Export tag
        id: vars
        run: echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

      - name: Build and publish
        run: |
          uv version $RELEASE_VERSION
          make build-and-publish
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}

  deploy-docs:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
